checks:
  php:
    code_rating: true

filter:
  excluded_paths:
    - tests/*
    - vendor/*

build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run

tools:
  external_code_coverage:
    runs: 30
